### ISSUE TITLE
The Python wrapper fails to locate the R script inside the container

### ISSUE THREAD

**Issue by ArtemSokolov** [labsyspharm/celluster#3]
Running
```
docker run --rm -v "$PWD":/data labsyspharm/celluster:1.0.1 python3 /app/celluster.py -i /data/unmicst-exemplar-001.csv -o /data/
```
from a directory containing `unmicst-exemplar-001.csv` produces:
```
subprocess.CalledProcessError: Command '['Rscript', 'celluster/runFastPG.r', '/data/clean_data.csv', '30', '1', '/data']' returned non-zero exit status 2.
```

The issue appears related to the assumed location of the Rscript: https://github.com/labsyspharm/celluster/blob/9d8cc2cc589213b492c9de357ea816bb536cd3e3/celluster.py#L107
which is not consistent with where the script is located inside the container.

**Comment by MattHodgman** [comment]
resolved by using os.path.realpath(__file__) to locate script
