### ISSUE TITLE
Resolve possible filename collisions

### ISSUE THREAD

**Issue by ArtemSokolov** [labsyspharm/celluster#8]
When the tool is used to process multiple input files residing in the same directory, e.g., 
```
python3 celluster.py unmicst-1.csv
python3 celluster.py unmicst-2.csv
python3 celluster.py unmicst-3.csv
....
```
the output files `cells.csv` and `clusters.csv` from multiple runs will overwrite each other.

Consider incorporating the original input filename into the output. For example, `python3 celluster.py unmicst-1.csv` would produce `uncmist-1-cells.csv` and `unmicst-2-clusters.csv`.

**Comment by MattHodgman** [comment]
That's a good idea.
